---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acapi-deployment
  labels:
    app: acapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acapi
  template:
    metadata:
      labels:
        app: acapi
    spec:
      containers:
      - name: acapi
        image: varnav/acapi
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: acapi-service
spec:
  selector:
    app: acapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-acapi
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: acapi-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: acapi-service
            port:
              number: 80
  ingressClassName: nginx